<html>
   <head>
      <title>parser сайта 03.ru</title>
      <style>
        table td {line-height: 36px;}
      </style>
   </head>
   <body>
      <form action="action.phtml" method="post">
      <table cellpadding="0" cellspacing="0">
         <tr>
            <td>откуда начинать парсить [url] - </td><td><input type="text" name="url" size="120"></td>
         </tr>
         <tr>
            <td>колличество переходов [number] - </td><td><input type="text" name="number"></td>
         </tr>
      </table>
      <input type="submit" name="parse-it">
   </body>
</html>
